spring:
  profiles: test
  jpa:
    hibernate:
      # drop n create table again, good for testing, comment this in production
      ddl-auto: create
name: test-YAML
environment: test
servers:
  - www.abc.test.com
  - www.zxc.test.com

---
spring:
  profiles: prod
name: prod-YAML
environment: production
servers:
  - www.abc.com
  - www.xyz.com

---
spring:
  profiles: dev
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
        show_sql: true
        format_sql: false
  datasource:
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5
    url: jdbc:postgresql://localhost:5432/social2
    username: postgres
    password: postgres
  messages:
    basename: i18n/messages
    encoding: UTF-8
    cache-seconds: -1
name: dev-YAML
environment: development
servers:
  - www.abc.com
  - www.xyz.com
