spring:
  profiles: test
  jpa:
    hibernate:
      # drop n create table again, good for testing, comment this in production
      ddl-auto: create
name: test-YAML
environment: test
servers:
  - www.abc.test.com
  - www.zxc.test.com

---
spring:
  profiles: prod
name: prod-YAML
environment: production
servers:
  - www.abc.com
  - www.xyz.com

---
spring:
  profiles: dev
  jpa:
    show-sql: true
  datasource:
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5
    url: jdbc:postgresql://localhost:5432/social2
    username: postgres
    password: postgres
name: dev-YAML
environment: development
servers:
  - www.abc.com
  - www.xyz.com
